import React,{useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{Building2,ClipboardList,FileCheck2,Euro,AlertTriangle,Camera,Cloud,BarChart3,BookOpen,Bot,Save,PlusCircle,MapPin,Download,RefreshCw,Trash2,Wand2,Search,Upload,CalendarDays,FileText,Calculator,Layers,Table2}from'lucide-react';
import jsPDF from'jspdf';
import * as XLSX from'xlsx';
import * as pdfjsLib from'pdfjs-dist/build/pdf.mjs';
import './style.css';
pdfjsLib.GlobalWorkerOptions.workerSrc=new URL('pdfjs-dist/build/pdf.worker.mjs',import.meta.url).toString();
const STORE='rjp_obras_pro_ia_v50_google';
const seedR=[
{id:'FER-VED-001',fonte:'RJP Ferrovia',cat:'Ferrovia',dom:'Vedações',desc:'Execução/substituição de vedação metálica',un:'m',mo:.40,prod:60,mat:'Postes; rede; fixações',eq:'Berbequim; viatura',pu:35},
{id:'FER-DRE-001',fonte:'RJP Ferrovia',cat:'Ferrovia',dom:'Drenagem',desc:'Limpeza/reperfilamento de valeta',un:'m',mo:.18,prod:120,mat:'-',eq:'Mini-escavadora; viatura',pu:9},
{id:'FER-AMV-001',fonte:'RJP Ferrovia',cat:'Ferrovia',dom:'AMV',desc:'Inspeção funcional de AMV e MPS',un:'un',mo:2.5,prod:4,mat:'Lubrificante; consumíveis',eq:'Ferramentas de via',pu:180},
{id:'ECA-COB-001',fonte:'ECAACR/RJP',cat:'Reabilitação',dom:'Coberturas',desc:'Substituição de cobertura em telha cerâmica',un:'m²',mo:.75,prod:25,mat:'Telha; ripado; acessórios',eq:'Andaime; ferramentas',pu:42},
{id:'ECA-FAC-001',fonte:'ECAACR/RJP',cat:'Reabilitação',dom:'Fachadas',desc:'Reparação e pintura de fachada',un:'m²',mo:.55,prod:35,mat:'Argamassa; primário; tinta',eq:'Andaime; lavadora',pu:28},
{id:'EDF-PIN-001',fonte:'RJP Edifícios',cat:'Edificação',dom:'Pinturas',desc:'Pintura interior de paredes',un:'m²',mo:.20,prod:90,mat:'Primário; tinta plástica',eq:'Rolo; trincha',pu:8}
];
const seedO=[{id:'obra-demo',nome:'Exemplo - Reabilitação de Edifício Ferroviário',cliente:'Infraestruturas de Portugal',local:'Linha do Oeste',inicio:'2026-06-01',fim:'2026-08-30',valor:85000,estado:'Em curso',progresso:35,obs:'Obra de demonstração.'}];
const empty={obra:{nome:'',cliente:'',local:'',inicio:'',fim:'',valor:'',estado:'Em preparação',progresso:0,obs:'',gps:''},orc:{obraId:'obra-demo',cap:'',subcap:'',artigo:'',desc:'',un:'m²',qtd:'',pu:'',iva:23},comp:{codigo:'',desc:'',un:'m²',mat:'',mo:'',eq:'',sub:'',desp:5,margem:15},med:{obraId:'obra-demo',orcId:'',mes:new Date().toISOString().slice(0,7),qtdContr:'',qtdAnt:'',qtdAtual:'',pu:'',obs:''},dia:{obraId:'obra-demo',data:new Date().toISOString().slice(0,10),meteo:'',equipa:'',trab:'',ocor:'',gps:'',ia:''},custo:{obraId:'obra-demo',data:new Date().toISOString().slice(0,10),desc:'',prev:'',real:'',tipo:'Custo'},ia:{titulo:'',texto:'',resultado:''},settings:{url:'',gptUrl:''}};
function uid(p){return p+'_'+Math.random().toString(36).slice(2,8)+'_'+Date.now().toString(36).slice(-5)}
function def(){return{obras:seedO,orcamentos:[],composicoes:[],medicoes:[],diarios:[],custos:[],licencas:[],ncs:[],fotos:[],rend:seedR,iaDocs:[],settings:{url:'',gptUrl:''}}}
function load(){try{return{...def(),...JSON.parse(localStorage.getItem(STORE)||'{}')}}catch{return def()}}
function App(){const[data,setData]=useState(load()),[tab,setTab]=useState('dash'),[q,setQ]=useState(''),[obra,setObra]=useState(empty.obra),[orc,setOrc]=useState(empty.orc),[comp,setComp]=useState(empty.comp),[med,setMed]=useState(empty.med),[dia,setDia]=useState(empty.dia),[custo,setCusto]=useState(empty.custo),[ia,setIa]=useState(empty.ia),[msg,setMsg]=useState('');
function persist(n){setData(n);localStorage.setItem(STORE,JSON.stringify(n));}
function add(k,obj,setter,blank,p){persist({...data,[k]:[{...obj,id:uid(p)},...(data[k]||[])]});setter(blank)}
function del(k,id){persist({...data,[k]:data[k].filter(x=>x.id!==id)})}
const tabs=[['dash','Dashboard',BarChart3],['obras','Obras',Building2],['orc','Orçamentos',Calculator],['comp','Composição',Layers],['med','Medições / Autos',Table2],['custos','Custos',Euro],['diario','Diário IA',ClipboardList],['ia','IA PDF / GPT',Bot],['google','Google',Cloud]];
const totalOrc=data.orcamentos.reduce((s,o)=>s+(+o.qtd||0)*(+o.pu||0),0),totalMed=data.medicoes.reduce((s,m)=>s+(+m.qtdAtual||0)*(+m.pu||0),0),totalReal=data.custos.reduce((s,c)=>s+(+c.real||0),0),desvio=totalMed-totalReal;
function gps(setter,obj){navigator.geolocation?.getCurrentPosition(p=>setter({...obj,gps:`${p.coords.latitude.toFixed(7)}, ${p.coords.longitude.toFixed(7)}`}),()=>setMsg('GPS indisponível.'),{enableHighAccuracy:true,timeout:15000})}
function calcComp(){const base=(+comp.mat||0)+(+comp.mo||0)+(+comp.eq||0)+(+comp.sub||0);const desp=base*(+comp.desp||0)/100;const marg=(base+desp)*(+comp.margem||0)/100;setComp({...comp,pu:(base+desp+marg).toFixed(2)})}
function usarComp(){setOrc({...orc,artigo:comp.codigo,desc:comp.desc,un:comp.un,pu:comp.pu||''});setTab('orc')}
function autoFromOrc(o){setMed({...empty.med,obraId:o.obraId,orcId:o.id,qtdContr:o.qtd,pu:o.pu,obs:o.desc});setTab('med')}
function medPercent(m){const c=+m.qtdContr||0;return c?(((+m.qtdAnt||0)+(+m.qtdAtual||0))/c*100).toFixed(1):'0.0'}
function diaIA(){const t=(dia.trab+' '+dia.ocor).toLowerCase();let r='Resumo IA local: '; if(t.includes('ved')||t.includes('rede'))r+='atividade de vedações; '; if(t.includes('cob')||t.includes('telha'))r+='atividade de cobertura; '; if(t.includes('hum')||t.includes('infil'))r+='possível humidade/infiltração; '; if(t.includes('atras'))r+='risco de atraso; '; if(r==='Resumo IA local: ')r+='sem alertas automáticos.'; setDia({...dia,ia:r})}
async function analisarIA(){const payload={app:'RJP Obras Pro IA',mode:'gpt_pdf_text',titulo:ia.titulo,texto:ia.texto,dados:{orcamentos:data.orcamentos,medicoes:data.medicoes,rend:data.rend}}; if(data.settings.gptUrl){try{const r=await fetch(data.settings.gptUrl,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const j=await r.json();setIa({...ia,resultado:j.resultado||JSON.stringify(j,null,2)});return}catch(e){setMsg('Falha no GPT remoto. Usei análise local.')}} const t=ia.texto.toLowerCase(); const nums=[...t.matchAll(/(\d+[\.,]?\d*)\s*(m2|m²|m3|m³|m|ml|un|kg)/g)].map(x=>`${x[1]} ${x[2]}`); setIa({...ia,resultado:`Análise local RJP:\n- Quantidades detetadas: ${nums.join(', ')||'nenhuma'}\n- Sugestão: confirmar unidades, associar ao artigo do orçamento e criar auto mensal.\n- Alertas: verificar trabalhos omissos, medições acumuladas e coerência com preço unitário.`})}
async function importarPdf(e){const f=e.target.files?.[0]; if(!f)return; setMsg('A ler PDF no navegador...'); try{const buf=await f.arrayBuffer(); const pdf=await pdfjsLib.getDocument({data:buf}).promise; let txt=''; for(let i=1;i<=pdf.numPages;i++){const pg=await pdf.getPage(i); const cont=await pg.getTextContent(); txt+=`\n\n--- Página ${i} ---\n`+cont.items.map(it=>it.str).join(' ')} setIa({...ia,titulo:ia.titulo||f.name,texto:(ia.texto?ia.texto+'\n\n':'')+txt.slice(0,120000)}); setMsg(`PDF importado: ${pdf.numPages} páginas.`)}catch(err){setMsg('Não consegui ler este PDF. Cola o texto ou usa OCR externo se for digitalização/imagem.')}}
function criarOrcDaIA(){const linhas=(ia.resultado||ia.texto||'').split(/\n|;/).map(x=>x.trim()).filter(Boolean); const novos=[]; linhas.forEach((l,idx)=>{const m=l.match(/(.{3,80}?)\s*[:=\-]?\s*(\d+[\.,]?\d*)\s*(m2|m²|m3|m³|ml|m|un|kg)/i); if(m){const qtd=parseFloat(m[2].replace(',','.'))||0; novos.push({...empty.orc,id:uid('orc'),obraId:orc.obraId||'obra-demo',cap:'IA/PDF',artigo:`IA-${String(idx+1).padStart(3,'0')}`,desc:m[1].replace(/^[-• ]+/,'').trim(),un:m[3],qtd,pu:''})}}); if(!novos.length){setMsg('Não encontrei linhas com quantidade + unidade para criar orçamento.');return} persist({...data,orcamentos:[...novos,...data.orcamentos]}); setMsg(`${novos.length} artigos criados a partir da IA/PDF. Confirma descrições, unidades e preços.`); setTab('orc')}
function pdfAuto(m){const d=new jsPDF();const val=(+m.qtdAtual||0)*(+m.pu||0);d.setFontSize(16);d.text('RJP Obras Pro IA - Auto de Medição',14,18);d.setFontSize(10);[['Mês',m.mes],['Obra',m.obraId],['Artigo',m.orcId||'-'],['Qtd. contratual',m.qtdContr],['Qtd. anterior',m.qtdAnt],['Qtd. atual',m.qtdAtual],['Percentagem acumulada',medPercent(m)+' %'],['Preço unitário',m.pu+' EUR'],['Valor do mês',val.toFixed(2)+' EUR'],['Observações',m.obs||'-']].forEach(([a,b],i)=>d.text(`${a}: ${b}`,14,34+i*8));d.save(`RJP_Auto_${m.mes||'medicao'}.pdf`)}
function pdf(){const d=new jsPDF();let y=16;d.setFontSize(18);d.text('RJP Obras Pro IA - Relatório',14,y);y+=10;d.setFontSize(10);[`Obras: ${data.obras.length}`,`Orçamentado: ${totalOrc.toFixed(2)} EUR`,`Medido/Autos: ${totalMed.toFixed(2)} EUR`,`Custo real: ${totalReal.toFixed(2)} EUR`,`Desvio: ${desvio.toFixed(2)} EUR`].forEach(l=>{d.text(l,14,y);y+=7});y+=5;d.setFontSize(13);d.text('Orçamentos',14,y);y+=7;d.setFontSize(8);data.orcamentos.forEach(o=>{if(y>280){d.addPage();y=18}d.text(`${o.cap||'-'} | ${o.artigo||'-'} | ${o.desc||'-'} | ${o.qtd} ${o.un} x ${o.pu} EUR`,14,y);y+=5});d.save('RJP_Obras_Pro_IA_Relatorio.pdf')}
function exportXlsx(){const wb=XLSX.utils.book_new();['obras','orcamentos','composicoes','medicoes','custos','diarios'].forEach(k=>XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(data[k]||[]),k));XLSX.writeFile(wb,'RJP_Obras_Pro_IA.xlsx')}
async function sync(){if(!data.settings.url){setMsg('Coloca primeiro o URL do Apps Script.');return} await fetch(data.settings.url,{method:'POST',mode:'no-cors',headers:{'Content-Type':'application/json'},body:JSON.stringify({app:'RJP Obras Pro IA',mode:'sync',payload:data})});setMsg('Sincronização enviada para Google Sheets/Drive.');}
async function googleBackup(){if(!data.settings.url){setMsg('Coloca primeiro o URL do Apps Script.');return} await fetch(data.settings.url,{method:'POST',mode:'no-cors',headers:{'Content-Type':'application/json'},body:JSON.stringify({app:'RJP Obras Pro IA',mode:'backup_drive',payload:data})});setMsg('Backup JSON enviado para Google Drive.');}
async function criarPastasGoogle(){if(!data.settings.url){setMsg('Coloca primeiro o URL do Apps Script.');return} await fetch(data.settings.url,{method:'POST',mode:'no-cors',headers:{'Content-Type':'application/json'},body:JSON.stringify({app:'RJP Obras Pro IA',mode:'create_folders',payload:{obras:data.obras}})});setMsg('Pedido de criação de pastas por obra enviado para o Google Drive.');}
async function exportarGoogleCompleto(){if(!data.settings.url){setMsg('Coloca primeiro o URL do Apps Script.');return} await fetch(data.settings.url,{method:'POST',mode:'no-cors',headers:{'Content-Type':'application/json'},body:JSON.stringify({app:'RJP Obras Pro IA',mode:'sync_full',payload:data})});setMsg('Exportação completa enviada: Sheets + Drive + pastas de obra.');}
const filtered=a=>(a||[]).filter(x=>JSON.stringify(x).toLowerCase().includes(q.toLowerCase()));
return <div className="app"><aside><div className="brand"><div className="logo">RJP</div><div><h1>RJP Obras</h1><p>Pro IA · V5 Google</p></div></div><nav>{tabs.map(([id,l,I])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><I size={18}/>{l}</button>)}</nav><button className="danger" onClick={()=>confirm('Repor dados?')&&persist(def())}><Trash2 size={16}/>Repor</button><div className="disclaimer">Software de apoio técnico. Validar sempre medições, preços e relatórios.</div></aside><main><header className="top"><div><h2>{tabs.find(t=>t[0]===tab)?.[1]}</h2><p>Orçamentos, composição de preços, medições, autos, custos, PDF, Excel, Google e IA.</p></div><div className="actions"><button onClick={pdf}><Download size={16}/>PDF</button><button onClick={exportXlsx}><Download size={16}/>Excel</button><button onClick={sync}><Cloud size={16}/>Sincronizar</button></div></header>{msg&&<div className="toast" onClick={()=>setMsg('')}>{msg}</div>}<div className="search"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Pesquisar..."/></div>
{tab==='dash'&&<><div className="cards"><Card t="Obras" v={data.obras.length}/><Card t="Orçamentado" v={totalOrc.toFixed(0)+' €'}/><Card t="Medido" v={totalMed.toFixed(0)+' €'}/><Card t="Custo real" v={totalReal.toFixed(0)+' €'}/><Card t="Desvio" v={desvio.toFixed(0)+' €'} warn={desvio<0}/></div><Panel title="Fluxo RJP Obras Pro IA"><p>PDF/Texto → IA → artigos e quantidades → orçamento → medições/autos → relatório PDF/Excel → Google Drive/Sheets.</p></Panel></>}
{tab==='obras'&&<Crud title="Registar obra" obj={obra} set={setObra} fields={['nome','cliente','local',['inicio','date'],['fim','date'],['valor','number'],['progresso','number'],'gps']} extra={<><Select label="Estado" v={obra.estado} set={v=>setObra({...obra,estado:v})} opts={['Em preparação','Em curso','Suspensa','Concluída','Encerrada']}/><TA label="Observações" v={obra.obs} set={v=>setObra({...obra,obs:v})}/></>} actions={<><button onClick={()=>gps(setObra,obra)}><MapPin size={16}/>GPS</button><button className="primary" onClick={()=>add('obras',obra,setObra,empty.obra,'obra')}><Save size={16}/>Guardar</button></>}/>} list={<List items={filtered(data.obras)} onDel={id=>del('obras',id)} render={o=><><b>{o.nome}</b><span>{o.cliente} · {o.local} · {o.estado}</span></>}/>} />}
{tab==='orc'&&<Crud title="Orçamentos / Mapa de quantidades" obj={orc} set={setOrc} fields={['obraId','cap','subcap','artigo','desc','un',['qtd','number'],['pu','number'],['iva','number']]} actions={<button className="primary" onClick={()=>add('orcamentos',orc,setOrc,empty.orc,'orc')}><PlusCircle size={16}/>Adicionar artigo</button>} list={<List items={filtered(data.orcamentos)} onDel={id=>del('orcamentos',id)} render={o=><><b>{o.cap} · {o.artigo}</b><span>{o.desc} · {o.qtd} {o.un} x {o.pu}€ = {((+o.qtd||0)*(+o.pu||0)).toFixed(2)}€</span><button onClick={()=>autoFromOrc(o)}>Criar auto</button></>}/>} />}
{tab==='comp'&&<Crud title="Composição de preços" obj={comp} set={setComp} fields={['codigo','desc','un',['mat','number'],['mo','number'],['eq','number'],['sub','number'],['desp','number'],['margem','number'],['pu','number']]} actions={<><button onClick={calcComp}><Wand2 size={16}/>Calcular PU</button><button className="primary" onClick={()=>add('composicoes',comp,setComp,empty.comp,'comp')}><Save size={16}/>Guardar</button><button onClick={usarComp}>Usar no orçamento</button></>} list={<List items={filtered(data.composicoes)} onDel={id=>del('composicoes',id)} render={c=><><b>{c.codigo} · {c.desc}</b><span>PU {c.pu}€/ {c.un} · Mat {c.mat} · MO {c.mo} · Eq {c.eq}</span></>}/>} />}
{tab==='med'&&<Crud title="Medições / Autos" obj={med} set={setMed} fields={['obraId','orcId',['mes','month'],['qtdContr','number'],['qtdAnt','number'],['qtdAtual','number'],['pu','number'],'obs']} actions={<button className="primary" onClick={()=>add('medicoes',med,setMed,empty.med,'med')}><FileCheck2 size={16}/>Guardar auto</button>} list={<List items={filtered(data.medicoes)} onDel={id=>del('medicoes',id)} render={m=><><b>{m.mes} · {m.orcId||'sem artigo'}</b><span>Atual {m.qtdAtual} · Acum. {((+m.qtdAnt||0)+(+m.qtdAtual||0)).toFixed(2)} / {m.qtdContr} · {medPercent(m)}% · Valor {((+m.qtdAtual||0)*(+m.pu||0)).toFixed(2)}€</span><button onClick={()=>pdfAuto(m)}>PDF Auto</button></>}/>} />}
{tab==='custos'&&<Crud title="Custos reais" obj={custo} set={setCusto} fields={['obraId',['data','date'],'desc',['prev','number'],['real','number'],'tipo']} actions={<button className="primary" onClick={()=>add('custos',custo,setCusto,empty.custo,'cus')}><Euro size={16}/>Guardar custo</button>} list={<List items={filtered(data.custos)} onDel={id=>del('custos',id)} render={c=><><b>{c.data} · {c.desc}</b><span>Previsto {c.prev}€ · Real {c.real}€ · {c.tipo}</span></>}/>} />}
{tab==='diario'&&<Crud title="Diário de obra com IA local" obj={dia} set={setDia} fields={['obraId',['data','date'],'meteo','equipa','gps']} extra={<><TA label="Trabalhos" v={dia.trab} set={v=>setDia({...dia,trab:v})}/><TA label="Ocorrências" v={dia.ocor} set={v=>setDia({...dia,ocor:v})}/><TA label="Resumo IA" v={dia.ia} set={v=>setDia({...dia,ia:v})}/></>} actions={<><button onClick={()=>gps(setDia,dia)}><MapPin size={16}/>GPS</button><button onClick={diaIA}><Bot size={16}/>Gerar resumo</button><button className="primary" onClick={()=>add('diarios',dia,setDia,empty.dia,'dia')}><Save size={16}/>Guardar</button></>} list={<List items={filtered(data.diarios)} onDel={id=>del('diarios',id)} render={d=><><b>{d.data} · {d.equipa}</b><span>{d.trab} · {d.ia}</span></>}/>} />}
{tab==='ia'&&<Panel title="Assistente IA para PDFs, cadernos de encargos e medições"><div className="formgrid"><Field label="Título/documento" v={ia.titulo} set={v=>setIa({...ia,titulo:v})}/><label>Importar PDF<input type="file" accept="application/pdf" onChange={importarPdf}/></label></div><TA label="Texto extraído do PDF ou notas" v={ia.texto} set={v=>setIa({...ia,texto:v})}/><div className="actions"><button className="primary" onClick={analisarIA}><Bot size={16}/>Analisar com IA</button><button onClick={criarOrcDaIA}><Calculator size={16}/>Criar artigos no orçamento</button></div><TA label="Resultado" v={ia.resultado} set={v=>setIa({...ia,resultado:v})}/><p className="hint">Agora já lê PDFs de texto diretamente no browser. PDFs digitalizados/imagens precisam de OCR ou análise GPT visual por backend seguro.</p></Panel>}
{tab==='google'&&<Panel title="Google Drive / Sheets / Pastas por Obra"><Field label="URL Apps Script Sync" v={data.settings.url} set={v=>persist({...data,settings:{...data.settings,url:v}})}/><Field label="URL Apps Script GPT" v={data.settings.gptUrl} set={v=>persist({...data,settings:{...data.settings,gptUrl:v}})}/><div className="actions"><button className="primary" onClick={sync}><RefreshCw size={16}/>Sincronizar Sheets</button><button onClick={googleBackup}><Cloud size={16}/>Backup Drive</button><button onClick={criarPastasGoogle}><Building2 size={16}/>Criar pastas por obra</button><button onClick={exportarGoogleCompleto}><Upload size={16}/>Exportação completa</button></div><Panel title="Estrutura criada no Drive"><pre>{`RJP_Obras_Pro_IA
 ├─ 01_Obras
 │   └─ Nome_da_Obra
 │      ├─ 01_Orçamentos
 │      ├─ 02_Medições_Autos
 │      ├─ 03_PDFs
 │      ├─ 04_Fotos
 │      ├─ 05_Diário_de_Obra
 │      └─ 06_Relatórios
 └─ 99_Backups_JSON`}</pre></Panel><p>Cola o ficheiro <b>google-apps-script/Code.gs</b> no Apps Script, publica como Web App e cola aqui o URL de implementação.</p></Panel>}
</main></div>}
function Card({t,v,warn}){return <div className={warn?'card warn':'card'}><small>{t}</small><b>{v}</b></div>}
function Panel({title,children}){return <section className="panel"><h3>{title}</h3>{children}</section>}
function Field({label,v,set,type='text'}){return <label>{label}<input type={type} value={v??''} onChange={e=>set(e.target.value)}/></label>}
function TA({label,v,set}){return <label className="wide">{label}<textarea value={v??''} onChange={e=>set(e.target.value)}/></label>}
function Select({label,v,set,opts}){return <label>{label}<select value={v} onChange={e=>set(e.target.value)}>{opts.map(o=><option key={o}>{o}</option>)}</select></label>}
function Crud({title,obj,set,fields=[],extra,actions,list}){return <Panel title={title}><div className="formgrid">{fields.map(f=>{const k=Array.isArray(f)?f[0]:f,typ=Array.isArray(f)?f[1]:'text';return <Field key={k} label={k} type={typ} v={obj[k]} set={v=>set({...obj,[k]:v})}/>})}{extra}</div><div className="actions">{actions}</div>{list}</Panel>}
function List({items,render,onDel}){return <div className="list">{items.map(x=><div className="item" key={x.id}><div>{render(x)}</div>{onDel&&<button className="mini" onClick={()=>onDel(x.id)}>Apagar</button>}</div>)}</div>}
createRoot(document.getElementById('root')).render(<App/>);
